### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by layerok** [adjustmentlayer/emojisushi-backend#9]

**Comment by sidhu2003** [comment]
Hey @layerok, I have experience in writing docker and docker-compose files, please assign this issue to me. You can check my previous work in the profile.

**Comment by layerok** [comment]
Hey @sidhu2003. You are on time. I just wanted to find someone who could help me. If you need any help, feel free to contact me anytime.

**Comment by sidhu2003** [comment]
Thank you @layerok, please assign this issue, so that I can start working on it 🤠
